on:
  pull_request:

name: "Trigger: Push action"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
